book/03-git-branching/1-git-branching.asc
book/03-git-branching/sections/basic-branching-and-merging.asc
book/03-git-branching/sections/branch-management.asc
book/03-git-branching/sections/nutshell.asc
book/03-git-branching/sections/rebasing.asc
book/03-git-branching/sections/remote-branches.asc
book/03-git-branching/sections/workflows.asc

I've started the translation of chapter 3, based on the Spanish translation of the [first version of the book](https://github.com/progit/progit/tree/master/es/03-git-branching).

Chapter 3. Branching

---

book/04-git-server/1-git-server.asc
book/04-git-server/sections/git-on-a-server.asc

Comienzo de la traducción del capítulo 4.

Traducción inicial del capítulo 4.

---

book/05-distributed-git/1-distributed-git.asc
book/05-distributed-git/sections/distributed-workflows.asc
status.json

Hola este es mi primer pull. He traducido lo que me ha dado tiempo. Mi intención es seguir colaborando con la traducción.

Traducción parcial C5 con apoyo de la v1

---

book/04-git-server/sections/generating-ssh-key.asc
book/04-git-server/sections/git-daemon.asc
book/04-git-server/sections/gitlab.asc
book/04-git-server/sections/gitweb.asc
book/04-git-server/sections/hosted.asc
book/04-git-server/sections/protocols.asc
book/04-git-server/sections/setting-up-server.asc
book/04-git-server/sections/smart-http.asc

Hola
He estado trabajando en traducir el capítulo 4, reutilizando en la medida de lo posible el texto de la versión 1 del libro.
Saludos a todos,

Traduccion C4

---

book/01-introduction/sections/first-time-setup.asc

Durante las pruebas de generación del libro he visto que se hace referencia a un estilo inexistente,
"ADVERTENCIA". He puesto el estilo original, "NOTE".

C1: minima correccion en first-time-setup.asc

---

book/06-github/1-github.asc
book/06-github/sections/1-setting-up-account.asc
book/06-github/sections/2-contributing.asc
book/06-github/sections/3-maintaining.asc

Hola
Sigo trabajando en esta traducción.
Envío la traducción inacabada de C6.
Sigo trabajando con ella.
Saludos a todos,

Traduccion C6

---

book/06-github/sections/2-contributing.asc
book/06-github/sections/4-managing-organization.asc
book/06-github/sections/5-scripting.asc

Hola a todos,
Os remito la traducción que quedaba pendiente del capítulo 6.
Un saludo!

Traduccion C6, segunda parte

---

book/08-customizing-git/1-customizing-git.asc
book/08-customizing-git/sections/attributes.asc
book/08-customizing-git/sections/config.asc
book/08-customizing-git/sections/hooks.asc
book/08-customizing-git/sections/policy.asc

Hola!
He traducido el capítulo 8, la verdad es que es poco mérito el mío porque he reutilizado todo lo que he
podido de la versión 1 del libro, revisando las diferencias con la nueva versión, claro; y corrigiendo alguna errata antigua.
Enjoy!

Traducción C8

---

book/A-git-in-other-environments/1-git-other-environments.asc
book/A-git-in-other-environments/sections/guis.asc

Traduccion Anexo A parte 1

---

book/02-git-basics/sections/recording-changes.asc

Update translations on some code commets on .gitignore explanation

Update translations on some code commets

---

book/05-distributed-git/sections/maintaining.asc

Traducción de 05-distributed-git/sections/maintaining.asc

---

book/introduction.asc

Introducción traducida. 
No se trata del Capítulo 1 sino de la Introducción previa.

Introducción traducida

---

book/02-git-basics/sections/recording-changes.asc

He corregido un error tipográfico:
as confirmado   --->  has confirmado

Error tipográfico corregido

---

book/B-embedding-git/1-embedding-git.asc
book/B-embedding-git/sections/command-line.asc
book/B-embedding-git/sections/libgit2.asc
book/C-git-commands/1-git-commands.asc
status.json

Hola Andrés,
aquí te envío la traducción del Apéndice C. 
Un saludo.

Apendice C traducido

---

book/01-introduction/sections/history.asc
book/02-git-basics/sections/recording-changes.asc
book/03-git-branching/sections/basic-branching-and-merging.asc
book/03-git-branching/sections/branch-management.asc
book/03-git-branching/sections/nutshell.asc
book/03-git-branching/sections/rebasing.asc
book/03-git-branching/sections/remote-branches.asc
book/03-git-branching/sections/workflows.asc
book/04-git-server/1-git-server.asc
book/04-git-server/sections/generating-ssh-key.asc
book/04-git-server/sections/git-daemon.asc
book/04-git-server/sections/git-on-a-server.asc
book/04-git-server/sections/gitweb.asc
book/04-git-server/sections/hosted.asc
book/04-git-server/sections/protocols.asc
book/04-git-server/sections/setting-up-server.asc
book/05-distributed-git/1-distributed-git.asc
book/05-distributed-git/sections/distributed-workflows.asc
book/06-github/sections/2-contributing.asc
book/06-github/sections/3-maintaining.asc
book/06-github/sections/5-scripting.asc
book/introduction.asc
book/preface.asc

adding corrections until chapter 6

---

book/10-git-internals/1-git-internals.asc
book/10-git-internals/sections/environment.asc
book/10-git-internals/sections/maintenance.asc
book/10-git-internals/sections/objects.asc
book/10-git-internals/sections/packfiles.asc
book/10-git-internals/sections/plumbing-porcelain.asc
book/10-git-internals/sections/refs.asc
book/10-git-internals/sections/refspec.asc
book/10-git-internals/sections/transfer-protocols.asc
status.json

Hola Andrés, ya he terminado de traducir el capítulo 10.
Un saludo.

Capitulo 10 traducido

---

book/01-introduction/sections/basics.asc

fixes progit/progit2-es#48
:lock:

Update typo "e"

---

TRANSLATION_NOTES.asc
book/10-git-internals/1-git-internals.asc

Part of the content was translated on an incorrect context or farther than necessary to Spanish equivalent.
This translation is more accurate in comparison to the original english source.
I made also the correspondent gender translation to articles in spanish.
In addition I show some of the more meaningful errors that justifies this pull request.
- un interface
The word "interface" does not  exists in spanish ,but interfaz.
- content-addresable
Contenido localizable is a better translation.

Corrections. Mistranslated words corrected. better translation.

---

.gitignore
book/04-git-server/sections/git-daemon.asc
book/04-git-server/sections/gitlab.asc
book/04-git-server/sections/protocols.asc
book/04-git-server/sections/setting-up-server.asc
book/04-git-server/sections/smart-http.asc
book/05-distributed-git/sections/maintaining.asc
book/06-github/sections/1-setting-up-account.asc
book/06-github/sections/3-maintaining.asc
book/06-github/sections/5-scripting.asc
book/08-customizing-git/sections/attributes.asc
book/08-customizing-git/sections/config.asc
book/08-customizing-git/sections/policy.asc
book/A-git-in-other-environments/sections/guis.asc

estandarizando glosario latino/español.
puede tener conflictos con .gitignore que agregué archivos que genera Eclispe.

cambio de 'fichero' a 'archivo'

---

book/01-introduction/1-introduction.asc
book/05-distributed-git/sections/distributed-workflows.asc
book/07-git-tools/1-git-tools.asc
book/07-git-tools/sections/replace.asc
book/09-git-and-other-scms/1-git-and-other-scms.asc
book/09-git-and-other-scms/sections/client-hg.asc
book/09-git-and-other-scms/sections/import-tfs.asc

Spanish Translate

---

book/07-git-tools/sections/revision-selection.asc
status.json

Traducción del contenido de revision-selection.asc
Christopher Díaz Riveros

Traducción de 07-git-tools/revision-selection.asc

---

book/07-git-tools/1-git-tools.asc
status.json

Traducción del primer texto del capítulo 7, los demás los voy a ir
presentando durante los siguientes días.
Christopher Díaz Riveros

Traducción book/07-git-tools/1-git-tools.asc

---

book/07-git-tools/sections/signing.asc
status.json

signing.asc + status.json updated

---

TRANSLATION_NOTES.asc

He añadido la traduccion adicional de esquema de ramificación a branching scheme

Añadida una traduccion adicional

---

book/07-git-tools/sections/rewriting-history.asc

progit2-es/book/07-git-tools/sections/rewriting-history.asc
Number of words: 846
Line:  192-329

spanish translation Part 2 rewriting-history.asc

---

book/07-git-tools/sections/stashing-cleaning.asc

progit2-es/book/07-git-tools/sections/stashing-cleaning.asc
Number of words: 1177
Line: 2-263

spanish translation stashing-cleaning.asc

---

book/07-git-tools/sections/advanced-merging.asc

progit2-es/book/07-git-tools/sections/advanced-merging.asc
Line: 159-426
Number of words: 1102

partial Spanish translation advanced-merging.asc

---

book/07-git-tools/sections/bundling.asc

progit2-es/book/07-git-tools/sections/bundling.asc
Line : 2-148
Number of words: 339

Spanish translation bundling.asc

---

book/09-git-and-other-scms/sections/client-svn.asc

progit2-es/book/09-git-and-other-scms/sections/client-svn.asc
line 212-381
Number of words 1020

 partial 2 update client-svn.asc

---

book/09-git-and-other-scms/sections/client-svn.asc

progit2-es/book/09-git-and-other-scms/sections/client-svn.asc
Line: 383-491
Number of words: 570

partial 3 update client-svn.asc

---

book/07-git-tools/sections/submodules.asc

471 translatable words have been translated to spanish.
Las sugerencias son bienvenidas. Continuaré traduciendo este archivo.

submodules.asc Traducido al Español (parcialmente)

---

book/07-git-tools/sections/reset.asc

Line: 2-175
Number of words:1202

Partial Update reset.asc

---

book/05-distributed-git/sections/contributing.asc

Number of words: 1104
Line: 101-379

Partial 2 update contributing.asc

---

book/05-distributed-git/sections/contributing.asc

Partial 4 update contributing.asc

---

book/A-git-in-other-environments/sections/zsh.asc

201 translatable words have been translated to spanish on this PR.

zsh.asc Traducido al Español

---

book/07-git-tools/sections/submodules.asc

I had to do it myself, jossue33's translation of this section isn't good

Second part submodules.asc

---

book/07-git-tools/sections/reset.asc

after reading jossue33's translation, I recommend you this one better

First part - Spanish translation of reset.asc file

---

book/02-git-basics/sections/recording-changes.asc

sistema de compilación en lugar de sistema de construcción

compilación en lugar de construcción

---

book/05-distributed-git/sections/distributed-workflows.asc

Hola @andres-mancera 👋 
Este Pull request soluciona el issue #127 donde se menciona que hace falta la traducción del capitulo 5.1 mencionado por @einsteinyh. 
Me avisas si necesita algun cambio. 👍

Traducción capitulo 5.1

---

book/05-distributed-git/sections/contributing.asc
book/09-git-and-other-scms/sections/client-p4.asc
book/09-git-and-other-scms/sections/client-svn.asc
book/09-git-and-other-scms/sections/client-tfs.asc
book/09-git-and-other-scms/sections/import-svn.asc

Sustituir la palabra **_sucursal_** por **_rama_**, más correcto y consistente con los demás capítulos.

Pequeño cambio de vocabulario

---

book/04-git-server/sections/protocols.asc

Les envío una corrección. Saludos.

Update: Procotolo ==>> Protocolo

---

book/03-git-branching/sections/basic-branching-and-merging.asc
book/03-git-branching/sections/branch-management.asc
book/03-git-branching/sections/nutshell.asc
book/03-git-branching/sections/rebasing.asc
book/03-git-branching/sections/remote-branches.asc
book/03-git-branching/sections/workflows.asc

Algunas correcciones ortográficas menores y cambios gramaticales. Donde considero lo admite cambié el término "coger" por "capturar".

Review about 0-3-git-branching finished

---

book/07-git-tools/sections/rerere.asc

Not much to comment. Great work!

Fix typo, Ahroa => Ahora

---

book/04-git-server/sections/generating-ssh-key.asc
book/04-git-server/sections/git-daemon.asc
book/04-git-server/sections/git-on-a-server.asc
book/04-git-server/sections/gitlab.asc
book/04-git-server/sections/gitweb.asc
book/04-git-server/sections/hosted.asc
book/04-git-server/sections/protocols.asc
book/04-git-server/sections/setting-up-server.asc
book/04-git-server/sections/smart-http.asc
book/05-distributed-git/sections/contributing.asc
book/05-distributed-git/sections/distributed-workflows.asc
book/05-distributed-git/sections/maintaining.asc

Hola de nuevo. La sección revisada viene detallada en el commit. En general he seguido el mismo patrón de trabajo que con las anteriores. Con excepción de un término que he resaltado : demonio.
Lo consideré algo pertinente ya que pertenece a la traducción literal de una referencia de la jerga técnica del programa. Aún así, espero vuestros comentarios al respecto.
El resto, como ya dije, es más de lo mismo.
Abrazo.

Review files in 04-git-server finished

---

book/04-git-server/sections/generating-ssh-key.asc
book/06-github/sections/1-setting-up-account.asc
book/06-github/sections/2-contributing.asc
book/06-github/sections/3-maintaining.asc
book/06-github/sections/4-managing-organization.asc
book/06-github/sections/5-scripting.asc

Hola nuevamente. He ralizado algunos cambios de sintaxis y correcciones ortográficas menores. Así como el resaltado de algunos términos técnicos que en la misma sección (y en un contexto similar desde mi punto de vista) aparecían de distinta forma, tanto en su resaltado como en la capitalización.  
Me surge una duda con respecto a que en algunos pasajes se menciona que las cuentas gratuitas de GitHub no admiten repositorios privados. Si mi información es correcta, desde que Microsoft adquirió el servicio, las cuentas gratuitas pueden contener hasta 5 repositorios privados. De ser así, quizás sería oportuno corregirlo, en caso contrario, podré aclarar mi confusión.
Gracias y un abrazo

Review on '06-github' sections finished.

---

book/06-github/sections/1-setting-up-account.asc
book/06-github/sections/3-maintaining.asc
book/06-github/sections/4-managing-organization.asc

Hola **@andres-mancera**. Envío las correcciones a las referencias sobre los repositorios privados gratuitos en GitHub en la sección 06 que precisamente se refiere a esto.
Saludos.

 Correction on Section '06-github' about free private repositories

---

book/07-git-tools/sections/reset.asc
book/07-git-tools/sections/revision-selection.asc
book/07-git-tools/sections/rewriting-history.asc
book/07-git-tools/sections/searching.asc
book/07-git-tools/sections/signing.asc
book/07-git-tools/sections/stashing-cleaning.asc
book/07-git-tools/sections/submodules.asc
book/07-git-tools/sections/subtree-merges.asc

Hola **@andres-mancera**. Envío un Pull Request sólo para consulta. He encerrado en un comentario la última oración del párrafo final de la sección *book/07-git-tools/sections/**reset.asc***. A mi parecer hay algo ahí que no debería estar. Parece sacada he insertada de otro contexto. Cuando puedas, por favor confírmamelo, pues si estoy en lo correcto, creo deberíamos evaluar eliminarla.
Gracias.
Un abrazo.

Pull Request updated. Finished review on Section '07-git-tools'

---

book/09-git-and-other-scms/sections/client-hg.asc
book/09-git-and-other-scms/sections/client-p4.asc
book/09-git-and-other-scms/sections/client-svn.asc
book/09-git-and-other-scms/sections/client-tfs.asc

Hola nuevamente **@andres-mancera**! Envío la revisión de los tres primeros capítulos de la sección 09. No hay grandes modificaciones, además de las banalidades usuales, traduje un par de oraciones dispersas que faltaban traducir al Español. Y a su vez devolví al Inglés todas las referencias a 'Subversion' que aparecían como 'Subversión'. Ya que aunque el término existe en el Español, en este caso concreto hace referencia a un nombre de producto literal.
No quise enviar más cambios en un único empuje ya que esta sección tiene capítulos bastaaante extensos, para facilitar las revisiones. :smiley: 
Saludos.

Review on Section 09 initialized (four first chapters concluded)

---

book/03-git-branching/sections/rebasing.asc

According to the english version "However, there is another way:
you can take the patch of the change that was introduced in C4 and
reapply it on top of C3." I belive C3 and C4 are changed.

Clarify basic rebase

---

book/04-git-server/sections/gitlab.asc
book/08-customizing-git/sections/config.asc
book/09-git-and-other-scms/sections/client-hg.asc
book/B-embedding-git/sections/jgit.asc

Since an update of build scripts, external URLs are checked for existence.

Fix broken external links

---

book/02-git-basics/sections/undoing.asc

Pequeño cambio para arreglar la traducción, así refleja correctamente la versión en inglés.
Soluciona #153

Fix translation
